import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { useContext } from 'react';
import { Store } from '../utils/Store';
import { useState } from 'react';
import { useEffect } from 'react';
import { Menu } from '@headlessui/react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { useSession } from 'next-auth/react';
import DropdownLink from './DropdownLink';

// this is the layout component, it is the base styling for all of the web pages going to be displayed

export default function Layout({ children }) {
	const { data: session, status } = useSession();

	// we are getting the state of the cart
	const { state } = useContext(Store);
	const { cart } = state;
	const [cartItemsCount, setCartItemsCount] = useState(0);
	useEffect(() => {
		setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
	}, [cart.cartItems]);

	return (
		<div>
			<Head>
				{/* this is saying that we are going to have a title (displayed in the tabs in the web browser and have the name of the page - provide) */}
				<title>Provide </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<ToastContainer position='bottom-center' limit={1} />
			{/* start of html  */}
			<div className='flex min-h-screen flex-col justify-between'>
				<nav className='flex h-12 items-center px-4 justify-between shadow-md bg-indigo-400'>
					<Link href='/ ' className='text-lg text-white font-bold '>
						Provide
					</Link>
					<div>
						<Link
							href='/cart'
							className='p-1 mr-6 text-white outline  rounded-md'
						>
							Cart
							{/* if cart.cartItem is greater than zero it means that you have
								at least one item within the cart  */}
							{cartItemsCount > 0 && (
								// we are using a reduce function on the cart.cartItems and an accumulator
								// to show the total number of items in the cart
								<span className='ml-1 rounded-full bg-white text-gray-700 px-2 py-0.5 text-s '>
									{cartItemsCount}
								</span>
							)}
						</Link>

						{/* below is where we are including the dropdown menu */}

						{/* checking to see if there is already a user logged in. If there is it shows the profile selection if not then it displays */}
						{status === 'loading' ? (
							'Loading'
						) : session?.user ? (
							<Menu as='div' className='relative inline-block'>
								<Menu.Button className='text-white'>
									{session.user.name}
								</Menu.Button>
								<Menu.Items className='absolute right-0 w-56 shadow-lg'>
									<Menu.Item>
										<DropdownLink className='dropdown-link' href='/profile'>
											Profile
										</DropdownLink>
									</Menu.Item>
								</Menu.Items>
							</Menu>
						) : (
							<Link href='/login' className='p-2'>
								Login
							</Link>
						)}
					</div>
				</nav>
				<main className='container m-auto mt-4 px-2 bg-white shadow-2xl rounded'>
					{children}
				</main>
				<footer className='flex text-white h-10 justify-center items-center shadow-inner bg-indigo-400'>
					Copyright © 2022 Provide
				</footer>
			</div>
		</div>
	);
}
