import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { useContext } from 'react';
import { Store } from '../utils/Store';
import { useState } from 'react';
import { useEffect } from 'react';

// this is the layout component, it is the base styling for all of the web pages going to be displayed

export default function layout({ title, children }) {
	// we are getting the state of the cart
	const { state, dispatch } = useContext(Store);
	const { cart } = state;
	const [cartItemsCount, setCartItemsCount] = useState(0);
	useEffect(() => {
		setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
	}, [cart.cartItems]);

	return (
		<>
			<Head>
				{/* this is saying that we are going to have a title (displayed in the tabs in the web browser and have the name of the page - provide) */}
				<title>{title ? title + ' - Provide' : 'Provide'} </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			{/* start of html  */}
			<div className='flex min-h-screen flex-col justify-between'>
				<header>
					{/* below is the nav and its styling */}
					<nav className='flex h-12 items-center px-4 justify-between shadow-md '>
						<Link href='/ ' className='text-lg font-bold'>
							Provide
						</Link>
						<div>
							<Link href='/cart' className='p-2'>
								Cart
								{/* if cart.cartItem is greater than zero it means that you have
								at least one item within the cart  */}
								{cartItemsCount > 0 && (
									// we are using a reduce function on the cart.cartItems and an accumulator
									// to show the total number of items in the cart
									<span className='ml-1 rounded-full bg-indigo-400 px-2 py-1 text-s font-bold text-white'>
										{cartItemsCount}
									</span>
								)}
							</Link>
							<Link href='/login' className='p-2'>
								Login
							</Link>
							<Link href='/aboutus' className='p-2'>
								About Us
							</Link>
						</div>
					</nav>
				</header>
				<main className='container m-auto mt-4 px-2'>{children}</main>
				<footer className='flex h-10 justify-center items-center shadow-inner'>
					Copyright © 2022 Provide
				</footer>
			</div>
		</>
	);
}
